### ISSUE TITLE
Header of DataGrids has a bug 

### ISSUE THREAD

**Issue by yooni126** [marpies/material-cyan-lime#1]
When we set datagrid.sortableColumns= true and touch their columns , the appearance of datagrid get a problem like this : 
![capture](https://user-images.githubusercontent.com/3766387/45342798-3f90e000-b5b4-11e8-84d4-7885fbd3beee.PNG)

**Comment by marpies** [comment]
Hi Yooni,

I can't reproduce this issue with source files or SWC file. It looks like some graphic assets may be missing and is not correctly linked with the project. Are you maybe using older version of the theme?

![img](https://user-images.githubusercontent.com/6077555/45344190-57139d00-b5a3-11e8-919b-d0bbe7880dda.png)

**Comment by yooni126** [comment]
ok , you said true, and now my my probelm has been fixed 👍
